# Generated by Django 2.0.5 on 2019-01-31 12:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requerimento', '0002_auto_20190129_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaARP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='assinante',
            name='alterado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assinante',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ataregistopreco',
            name='alterado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ataregistopreco',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='alterado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='centrocusto',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='alterado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimento',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requerimentoarp',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretaria',
            name='alterado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='criado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtoarp',
            name='produto',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='assinaturaarp',
            name='assinante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimento.assinante'),
        ),
        migrations.AddField(
            model_name='assinaturaarp',
            name='requerimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requerimento.RequerimentoARP'),
        ),
    ]
