# Generated by Django 2.0.5 on 2019-02-01 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requerimento', '0003_auto_20190131_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrequerido',
            name='produto',
        ),
        migrations.AddField(
            model_name='itemrequerido',
            name='descricao',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
