# Generated by Django 2.1.5 on 2019-02-05 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('requerimento', '0004_auto_20190201_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimento',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
