# Generated by Django 2.1.5 on 2019-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=250)),
                ('criado', models.DateField(auto_now_add=True)),
                ('alterado', models.DateField(auto_now=True)),
            ],
        ),
    ]
