# Generated by Django 2.1.5 on 2019-01-21 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certidao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['label']},
        ),
    ]
